### PR TITLE
NVidia deadlock fix + some other fixes

### LINKED ISSUE #30: QueryPerformanceCounter issues
Some external DLLs (notably, NVidia's graphics driver DLLs) (who knows, maybe some games do this as well) are calling QueryPerformanceCounter() / <...>Frequency() similarly to this:

```
QueryPerformanceFrequency(&Freq);
QueryPerformanceCounter(&PerfCount);
do
    QueryPerformanceCounter(&Temp);
while (Temp == PerfCount);
```

in the main thread (usually before any graphics were initialized, so before any frames are being drawn, which means before any time starts to pass), which results in an indefinite loop.

In the case with NVidia's graphics DLLs, it's basically impossible to launch any games under Hourglass because that piece of code is reached inside `Direct3DCreate9()`.

A possible fix would be to call the original QPC() / QPF() in any case where caller is untrusted, however I'm afraid that this can cause indeterministic behavior (if the said external DLL measures time for something important in the game).

If you're experiencing the mentioned issues with `Direct3DCreate9()` a quick and dirty fix is to call the original QPC() / QPF() when inside `Direct3DCreate9()`.

### PR DESCRIPTION
**Pull request by YaLTeR**
- Resolves #30 (finally!)
- Adds a D3D9 test (which surprisingly runs well on Appveyor)
- Strips stuff from basic_timing that caused some questionable behavior by really questionable GDI hook code
- Fixes test_runner being unable to overwrite the failed logs
- Fixes trusted caller response (and any other response while we're at it) (actually by Warepire)
- Makes VC++ runtime libs trusted (because some C++ calls go through that)
- Fixes sync issues caused by incorrect `Sleep` being called by code outside of `Hooks`
- Comments out subticks for now (they cause issues with the number of time calls from basic_timing)
- Comments out some annoying debug logging
- Fixes random crashes due to `LOAD_DLL_DEBUG_EVENT` receiving null `hFile`

### CODE REVIEW

File: source/tests/d3d9/logger.cpp [hunk 1]
```diff
@@ -0,0 +1,26 @@
+/*
```
Comment (Warepire) [inline source/tests/d3d9/logger.cpp]: Instead of duplicating this, can you create a tests/shared or something?
